import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
// import googleIcon from "../../public/icons/google.svg";
// import facebookIcon from "../../public/icons/facebook.svg";
// import linkedInIcon from "../../public/icons/linkedIn.svg";
// import instagramIcon from "../../public/icons/instagram.svg";
// import skypeIcon from "../../public/icons/skype.svg";
// import twitterIcon from "../../public/icons/twitter.svg";
import upGreenWave from "../../public/icons/up-green-wave.svg";
import { log } from "console";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children }: Readonly<{ children: React.ReactNode }>
) {
  /* ===== variables ===== */
  const socialMediaNames: string[] = [
    "google", 
    "facebook", 
    "linkedIn", 
    "instagram", 
    "skype", 
    "twitter"
  ];

  /* ===== Renders ===== */
  const renderSocialMediaLinksIcons = () => 
    socialMediaNames.map( name =>
      <li key={name}>
        <button>
          <Link href={`${name} URl`}>
            <Image 
              src={`/icons/${name}.svg`} alt={`${name} icon`}
              className="max-w-full" width={45} height={45}
            />
          </Link>
        </button>
      </li>
    )

  return (
    <html lang="en">
      <body className="container mx-auto bg-primary text-white font-normal">
        {children}
        <footer className="greenArticle article relative px-5 flex pb-5">
          <Image 
            src={upGreenWave} alt="Green Wave Icon" 
            className="wave absolute bottom-full"
          />
          <nav className="flex flex-1 items-end">
            <ul className="linksList flex items-center gap-5">
              {renderSocialMediaLinksIcons()}
            </ul>
          </nav>
          <article className="mr-5">
            <h3 className="font-medium text-4xl mb-5">Contact Us</h3>
            <form className="">
              <div className="formDataContainer flex items-center gap-4 mb-3">
                <div className="inputsContainer flex-1  flex flex-col gap-3">
                  <input 
                    type="text" placeholder="Your Name" 
                    className="py-1 px-3 rounded-md"
                  />
                  <input 
                    type="text" placeholder="Your Email" 
                    className="py-1 px-3 rounded-md"
                  />
                </div>
                <textarea 
                  name="TODO WHAT THIS FOR" id="message" placeholder="Your Message"
                  className="flex-1 w-96 h-24 resize-none py-1 px-3 rounded-md" 
                />
              </div>
              <input 
                type="button" value="Send" 
                className="block bg-primary px-4 py-1 ml-auto rounded-lg"
              />
            </form>
          </article>
        </footer>
      </body>
    </html>
  );
}





// TODO: How is better in a form The Input button or a normal button
// TODO: Check the images and edit their import
// TODO: Upload unknown images size


